#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


#
# Browser
#
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export GIT_EDITOR='nvim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
cdpath=(
  $cdpath
  $HOME
  $PROJECT_HOME
  $HOME/go/src/github.com/ecnahc515
  $HOME/go/src/github.com/coreos
  $HOME/go/src/github.com/coreos-inc
  $HOME/go/src/github.com/operator-framework
  $HOME/go/src/github.com
)


# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/bin
  $HOME/dotfiles/custom_bins
  $HOME/.tmuxifier/bin
  $GOPATH/bin
  $GOROOT/bin
  $HOME/Library/Python/2.7/bin
  /usr/local/{bin,sbin}
  /usr/local/opt/python/libexec/bin
  "${KREW_ROOT:-$HOME/.krew}/bin"
  /usr/local/opt/curl/bin
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
